# Generated by Django 5.1.2 on 2024-10-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.CharField(default='Sin asignar', max_length=50),
        ),
    ]
